entsoe:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account-json
      project: "{{ env_var('DBT_ENV_SECRET_DEV_PROJECT_ID') }}"
      dataset: entsoe_dw
      location: EU
      job_execution_timeout_seconds: 300
      job_retries: 1
      priority: interactive
      threads: 4
      
      keyfile_json:
        type: service_account
        project_id: "{{ env_var('DBT_ENV_SECRET_DEV_PROJECT_ID') }}"
        private_key_id: "{{ env_var('DBT_ENV_SECRET_DEV_KEYFILE_PRIVATE_KEY_ID') }}"
        private_key: "{{ env_var('DBT_ENV_SECRET_DEV_KEYFILE_PRIVATE_KEY') }}"
        client_email: "{{ env_var('DBT_ENV_SECRET_DEV_KEYFILE_CLIENT_EMAIL') }}"
        client_id: "{{ env_var('DBT_ENV_SECRET_DEV_KEYFILE_CLIENT_ID') }}"
        auth_uri: https://accounts.google.com/o/oauth2/auth
        token_uri: https://oauth2.googleapis.com/token
        auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
        client_x509_cert_url: "{{ env_var('DBT_ENV_SECRET_DEV_KEYFILE_CLIENT_X509_CERT_URL') }}"
